name: Build, Version, and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Adjust this to match your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        run: |
          echo "ECR Registry URL: ${{ secrets.ECR_REGISTRY }}"
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build Docker image
        run: |
          docker build -t dipl-rad-tours-service:latest .

      - name: Tag Docker image
        run: |
          echo "Tagging Docker image with ECR URL"
          docker tag dipl-rad-tours-service:latest ${{ secrets.ECR_REGISTRY }}/dipl-rad-tours-service:latest

      - name: Push Docker image to ECR
        run: |
          echo "Pushing Docker image to ECR"
          docker push ${{ secrets.ECR_REGISTRY }}/dipl-rad-tours-service:latest
